# Generated by Django 3.2 on 2021-04-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Janer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janer_name', models.CharField(max_length=200, verbose_name='نوع ژانر')),
                ('janer_tozihat', models.CharField(max_length=200, verbose_name='معرفی ژانر')),
                ('image_janer', models.ImageField(null=True, upload_to='janerimages', verbose_name='عکس ژانر')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر',
            },
        ),
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('jens', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], null=True, verbose_name='جنسیت')),
                ('imail_name', models.CharField(max_length=100, null=True, verbose_name='ایمیل')),
                ('adress_name', models.CharField(max_length=200, verbose_name='آدرس محل سکونت')),
                ('phone_name', models.CharField(default='09', max_length=11, verbose_name='شماره تماس')),
                ('image_name', models.ImageField(null=True, upload_to='profileimages', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='sans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sans', models.DateTimeField(verbose_name='زمان سانس')),
                ('local_sans', models.CharField(max_length=500, verbose_name='مکان سانس')),
                ('status_sans', models.IntegerField(choices=[(1, ' سانس شروع شده است'), (2, ' سانس تمام شده است'), (3, 'در حال فروش بلیط'), (4, ' سانس کنسل شده است'), (5, 'بلیط تمام شده است')], verbose_name='وضعیت سانس')),
                ('zarfiat_sans', models.IntegerField(verbose_name='ظرفیت سانس')),
            ],
            options={
                'verbose_name': 'سانس ها',
                'verbose_name_plural': 'سانس ها',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_film', models.CharField(max_length=200, verbose_name='نام فیلم')),
                ('karghardan', models.CharField(max_length=50, null=True, verbose_name=' کارگردان')),
                ('name_bazigaran', models.CharField(max_length=200, verbose_name='نام بازیگران')),
                ('tozihat', models.CharField(max_length=500, verbose_name='درباره فیلم')),
                ('time_film', models.DateField(verbose_name='سال تولید فیلم')),
                ('image_film', models.ImageField(null=True, upload_to='filmimages', verbose_name='عکس فیلم')),
                ('name_janer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.janer', verbose_name='نوع ژانر')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم',
            },
        ),
    ]
