# Generated by Django 3.2 on 2021-04-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan', models.IntegerField(choices=[(1, 'آذربایجان شرقی'), (2, 'آذربایجان غربی'), (3, 'اردبیل'), (4, 'اصفهان'), (5, 'البرز'), (6, 'ایلام'), (7, 'بوشهر'), (8, 'تهران'), (9, 'چهارمحال و بختیاری'), (10, 'خراسان جنوبی'), (11, 'خراسان رضوی'), (12, 'خراسان شمالی'), (13, 'خوزستان'), (14, 'زنجان'), (15, 'سمنان'), (16, 'سیستان و بلوچستان'), (17, 'فارس'), (18, 'قزوین'), (19, 'قم'), (20, 'کردستان'), (21, 'کرمان'), (22, 'کرمانشاه'), (23, 'کهگیلویه و بویراحمد'), (24, 'گلستان'), (25, 'گیلان'), (26, 'لرستان'), (27, 'مازندران'), (28, 'مرکزی'), (29, 'هرمزگان'), (30, 'همدان'), (31, 'یزد')], verbose_name='استان ها')),
                ('name_location', models.CharField(max_length=100, verbose_name='نام سینما')),
                ('adress_location', models.CharField(max_length=300, verbose_name='ادرس سینما')),
            ],
            options={
                'verbose_name': 'مکان سینما',
                'verbose_name_plural': 'مکان سینما',
            },
        ),
    ]
