# Generated by Django 3.2 on 2021-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='time_film',
            field=models.DateField(null=True, verbose_name='سال تولید فیلم'),
        ),
        migrations.AlterField(
            model_name='location',
            name='ostan',
            field=models.IntegerField(choices=[(4, 'اصفهان'), (8, 'تهران'), (11, 'مشهد'), (17, 'شیراز'), (19, 'قم'), (28, 'مرکزی')], verbose_name='استان ها'),
        ),
    ]
