# Generated by Django 3.2 on 2021-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20210427_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='sans',
            name='price_sans',
            field=models.CharField(default='تومان', max_length=30, null=True, verbose_name='هزینه سانس'),
        ),
    ]
