# Generated by Django 3.2 on 2021-05-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_location_phone_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name_film',
            field=models.SlugField(allow_unicode=True, max_length=200, verbose_name='نام فیلم'),
        ),
    ]
