# Generated by Django 3.2 on 2021-05-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_film_name_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='namber_film',
            field=models.CharField(max_length=100, null=True, verbose_name='سریال فیلم'),
        ),
    ]
