# Generated by Django 3.2 on 2021-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_film_namber_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age_film',
            field=models.IntegerField(choices=[(1, 'تماشا افراد زیر 9 سال ممنوع است'), (2, 'تماشا افراد زیر 14 سال ممنوع است'), (3, 'مناسب برای افراد بالای 18 سال'), (4, 'تماشا برای افرادی که ناراحتی قلبی دارند ممنوع است')], null=True, verbose_name='محدودیت های تماشا فیلم'),
        ),
        migrations.AddField(
            model_name='film',
            name='country_film',
            field=models.CharField(max_length=50, null=True, verbose_name='محصول کشور'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_time',
            field=models.TimeField(null=True, verbose_name='تایم فیلم'),
        ),
    ]
