# Generated by Django 3.2 on 2021-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20210502_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='film',
            name='age_film',
            field=models.IntegerField(choices=[(1, 'مناسب برای تمام سنین'), (6, 'مناسب برای کودکان زیر 9 سال'), (2, 'تماشا افراد زیر 9 سال ممنوع است'), (3, 'تماشا افراد زیر 14 سال ممنوع است'), (4, 'مناسب برای افراد بالای 18 سال'), (5, 'تماشا برای افرادی که ناراحتی قلبی دارند ممنوع است')], null=True, verbose_name='محدودیت های تماشا فیلم'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tozihat',
            field=models.CharField(max_length=1000, verbose_name='درباره فیلم'),
        ),
    ]
