# Generated by Django 3.2 on 2021-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20210504_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='password',
            field=models.CharField(max_length=100, verbose_name='رمز عبور'),
        ),
    ]
