# Generated by Django 3.2 on 2021-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_name_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sans',
            name='namber_sans',
            field=models.CharField(max_length=100, null=True, verbose_name='سریال سانس'),
        ),
    ]
