# Generated by Django 3.2 on 2021-05-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_sans_namber_sans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='Profile',
        ),
    ]
