# Generated by Django 3.2 on 2021-05-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_rename_name_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
