# Generated by Django 3.2 on 2021-05-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20210509_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'فیلم ها', 'verbose_name_plural': 'فیلم ها'},
        ),
        migrations.AlterModelOptions(
            name='janer',
            options={'verbose_name': 'ژانر ها', 'verbose_name_plural': 'ژانر ها'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'سینما ها', 'verbose_name_plural': 'سینما ها'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل ها', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
