# Generated by Django 3.2 on 2021-05-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20210509_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='time_film',
            field=models.DateTimeField(null=True, verbose_name='زمان تولید فیلم'),
        ),
    ]
